# Generated by Django 3.0.8 on 2020-07-25 06:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('organizer', models.CharField(max_length=9)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), size=None)),
            ],
        ),
    ]
