# Generated by Django 3.0.8 on 2020-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200725_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='start_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
